version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch
    steps:
      - checkout
      - run: sudo apt-get update
      - run:
          name: Install locales
          command: |
              sudo locale-gen fr_FR.UTF-8
              sudo locale-gen fr fr_FR fr_FR.UTF-8
              sudo dpkg-reconfigure locales
      - run:
          name: Install python-virtualenv
          command: sudo apt-get install python-virtualenv
      - run:
          name: install python dependencies
          command: |
              mkdir -p ./venv
              virtualenv ./venv
              . venv/bin/activate
              pip install pelican webassets cssmin markdown
      - run: mkdir output
      - run:
          name: make html
          command: |
              . venv/bin/activate
              make html
      - run: pip install -t lib -r requirements.txt
      - run: mkdir -p /tmp/workspace
      - run:
          name: Copy pathes to be persisted in workspace
          command: |
              cp -R output /tmp/workspace
              cp -R lib /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
              - output
              - lib
  deploy:
    filters:
     branches:
       only:
          - master
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
              echo $CLIENT_SECRET | base64 -d > ${HOME}/gcloud-service-key.json
              gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
              gcloud config set project $GCLOUD_PROJECT
      - run:
          name: Deploy to Google App Engine
          command: |
              cp -R /tmp/workspace/* .
              gcloud -q app deploy app.yaml --promote
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
